name: Release (API Pessoas)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: read

jobs:
  release:
    name: Criar release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Verificar Maven Wrapper
        run: |
          if [ ! -f "pessoas/mvnw" ]; then
            echo "mvnw n√£o encontrado"
            exit 1
          fi

      - name: Build jar
        working-directory: pessoas
        run: |
          chmod +x mvnw
          ./mvnw -B clean package -DskipTests=true
        env:
          MAVEN_OPTS: -Xmx2G

      - name: Gerar changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: ".github/changelog-config.json"
          toTag: ${{ github.ref_name }}
          outputFile: release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Criar release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          body_path: release_notes.md
          files: |
            pessoas/target/api-pessoas-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
